name: hyll_test_task
description: Hyll test project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build_runner: 2.4.6
  cached_network_image: 3.2.3
  chopper: 6.1.4
  flutter_bloc: 8.1.3
  freezed: 2.3.5
  freezed_annotation: 2.2.0
  get_it: 7.6.0
  json_serializable: 6.7.1
  json_annotation: 4.8.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: 6.0.3
  flutter_lints: 2.0.2

flutter:
  uses-material-design: true